name: coverswift

services:
  app:
    image: php:8.3-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
    depends_on:
      - caddy

  caddy:
    image: caddy:2.7
    container_name: laravel_caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - .:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "127.0.0.1:8000:80"

volumes:
  caddy_data:
  caddy_config: